[tool.poetry]
name = "ssticket"
version = "0.1.0"
description = ""
authors = ["jerry <jestar@no.reply>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.0"
fastapi-sqlalchemy = "^0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
